### ISSUE TITLE
Can I use my own mask?

### ISSUE THREAD

**Issue by Royalvice** [GouravWadhwa/Hypergraphs-Image-Inpainting#10]
I want to know whether i can use my own random mask for testing?
Thanks

**Comment by alexmi256** [comment]
This isn't possible currently. I've added a extra random mask types in https://github.com/alexmi256/Hypergraphs-Image-Inpainting and this was next on my todo list at https://github.com/alexmi256/Hypergraphs-Image-Inpainting/pull/5/files but I'm not that familiar with tensorflow and have not had much time to try out how to pair up the image and image mask

**Comment by GouravWadhwa** [comment]
So I have added this feature.
Now you can test with your own mask using generate_mask option in tes_options.py. The only thing is you have to list all the images in a file with the following format:
Image1.jpg Mask1.png
Image1.jpg Mask1.png
Give --generate_mask 0 and provide the path to mas

**Comment by GouravWadhwa** [comment]
So I have added this feature.
Now you can test with your own mask using generate_mask option in test_options.py. The only thing is you have to list all the images in a file with the name of image and the mask in the following format
Image1.jpg Mask1.png
Image2.jpg Mask2.png
...

Give --generate_mask 0 and provide the path to test_file and you can test on your own mask.
Hope this helps
Please let me know if there is still any issue

**Comment by Royalvice** [comment]
thanks, it helps a lot！！！

**Comment by zhangshilong2000** [comment]
> 谢谢，它有很大帮助!!

你好，这个怎么设置使用自己的掩码？
