### ISSUE TITLE
Train with 512*512 images

### ISSUE THREAD

**Issue by Royalvice** [GouravWadhwa/Hypergraphs-Image-Inpainting#11]
tensorflow.python.framework.errors_impl.InvalidArgumentError: ConcatOp : Dimensions of inputs should match: shape[0] = [1,64,64,256] vs. shape[1] = [4,32,32,512] [Op:ConcatV2] name: concat
It looks like 512*512 image doesn't match the inputs of model

**Comment by Royalvice** [comment]
the same problem also in testing

**Comment by GouravWadhwa** [comment]
Sorry for the late response.
This issue was the model was specifically designed for only 256, 256 inputs.
I have changed it and it can work for different input sizes.
