### ISSUE TITLE
Can I test an image without a mask?

### ISSUE THREAD

**Issue by yc-cui** [GouravWadhwa/Hypergraphs-Image-Inpainting#16]
I mean, in real life, we just have a damaged picture. How can I inpaint it when I don't have a mask? Is there any algorithm that detects the mask automatically?

**Comment by GouravWadhwa** [comment]
Currently, for this method, this is not possible. But if you can share a damaged image we can think about generating a mask from the image and then using this method. 
Basically, this method can easily be extended if we can somehow generate the mask.

**Comment by yc-cui** [comment]
> Currently, for this method, this is not possible. But if you can share a damaged image we can think about generating a mask from the image and then using this method. Basically, this method can easily be extended if we can somehow generate the mask.

Thank you for your reply. However, I have no idea how to generate the mask.
