### ISSUE TITLE
How to replace the mask

### ISSUE THREAD

**Issue by fittiing** [GouravWadhwa/Hypergraphs-Image-Inpainting#18]
Hello, I want to use my own mask. Where should I modify it

**Comment by GouravWadhwa** [comment]
What do you want to replace the mask to?

**Comment by fittiing** [comment]
How to integrate one's own mask dataset into a snowflake shaped mask instead?

**Comment by GouravWadhwa** [comment]
Currently there is no option to have a custom mask.
