### ISSUE TITLE
Question about places2 dataset

### ISSUE THREAD

**Issue by kiet13** [GouravWadhwa/Hypergraphs-Image-Inpainting#4]
Hi,

Thanks for publishing this great work!
I have a question about how you extract test set from places2 dataset.

In the papers, you said that you only use 10 categories of places2 dataset for training. I guess you only use the same categories for test set, too.  As I know, places2 dataset offical website did not public category of each image in test set. How can you evaluate the model on this dataset? Do you know how to retrieve categories from test set?

**Comment by GouravWadhwa** [comment]
The testing for the Places2 dataset was done on images of the validation dataset for the same 10 categories.
We will further be releasing more qualitative and quantitative results for the Places2 dataset.

Thank you
Gourav
