### ISSUE TITLE
Great Work! Do you have 512x680 pretrained model?

### ISSUE THREAD

**Issue by amarese** [GouravWadhwa/Hypergraphs-Image-Inpainting#5]
It looks excellent on your paper. I just downloaded your 256x256 pretrained model and run. But it was not very good as I expected when I saw your paper. It seems you have another pretrained model with 512x680 size. Can you make it public?

**Comment by GouravWadhwa** [comment]
Hi,
The input size for the image should be 256x256, otherwise, the network would not produce fine results because of the graphs used by the network. 
We will be soon releasing the training code and then you can train the network on the given size.

Thank you
Gourav
