### ISSUE TITLE
请问不能训练自己的模型吗，只能测试？

### ISSUE THREAD

**Issue by ZHANG-hengzhi** [GouravWadhwa/Hypergraphs-Image-Inpainting#6]

**Comment by GouravWadhwa** [comment]
The training code has been published if you still got any doubt please let me know

**Comment by ZHANG-hengzhi** [comment]
I very much look forward to your providing the training code. Thank you very much.



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "GouravWadhwa/Hypergraphs-Image-Inpainting"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月6日(星期天) 凌晨2:38
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [GouravWadhwa/Hypergraphs-Image-Inpainting] 请问不能训练自己的模型吗，只能测试？ (#6)





 
The training code has been published if you still got any doubt please let me know
