### ISSUE TITLE
test.py doesn't inpaint image

### ISSUE THREAD

**Issue by asdj32n12dk** [GouravWadhwa/Hypergraphs-Image-Inpainting#9]
Hello, I just launch test.py and instead of inpainting - it just fill the mask with black. (It's happening because prediction_coarse magnitude it too low)
![Places365_val_00032545_00%-05%_02 27%_Places365_test_00176672](https://user-images.githubusercontent.com/87753156/126487210-00f335bf-4f64-4ed2-be96-52919cc32930.png)

**Comment by GouravWadhwa** [comment]
Hi,
Can you please explain what you are doing.
Because I think you are not loading the pretrained model correctly.
Please download the pretrained model and give the correct prefix while testing.

Thank you
Gourav

**Comment by asdj32n12dk** [comment]
ohh, sorry, got it. Thanks!

I was using wrong path for checkpoint.restore() `"pretrained_models/Random/places2_256x256_random_mask.index"` instead of
 `"pretrained_models/Random/places2_256x256_random_mask"`
